import { useState } from 'react'
import { Avatar, Box, Button, Chip, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { Add, Search } from '@mui/icons-material'
import { useDispatch, useSelector } from 'react-redux'
import { addProduct, deleteProduct, fetchProducts, updateProduct } from '../features/products/productsSlice'
import Shell from '../components/Shell'; import navItems from '../components/navItems'; import PageHeader from '../components/PageHeader'; import Status from '../components/Status'; import ProductDialog from '../components/ProductDialog'

const AdminProducts = () => { const dispatch = useDispatch(); const { items, categories, status } = useSelector((state) => state.products); const [query, setQuery] = useState(''); const [dialog, setDialog] = useState(null); const [notice, setNotice] = useState(''); const filtered = items.filter((product) => product.title.toLowerCase().includes(query.toLowerCase())); return <Shell admin navItems={navItems}><PageHeader eyebrow="Admin tools" title="Product management" subtitle="Manage your catalogue and local overrides." action={<Button variant="contained" startIcon={<Add />} onClick={() => setDialog({})}>Add product</Button>} /><Box className="toolbar"><TextField size="small" placeholder="Search catalogue" value={query} onChange={(event) => setQuery(event.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search fontSize="small" /></InputAdornment> } }} /></Box><Status status={status} error="Unable to load products" retry={() => dispatch(fetchProducts())} />{status === 'succeeded' && <Paper className="table-wrap"><Table size="small"><TableHead><TableRow><TableCell>Product</TableCell><TableCell>Category</TableCell><TableCell>Price</TableCell><TableCell>Stock</TableCell><TableCell>Rating</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{filtered.map((product) => <TableRow key={product.id}><TableCell><Stack direction="row" spacing={1} alignItems="center"><Avatar variant="rounded" src={product.thumbnail} /><Typography>{product.title}</Typography></Stack></TableCell><TableCell>{product.category}</TableCell><TableCell>${product.price}</TableCell><TableCell><Chip size="small" label={product.stock} color={product.stock < 20 ? 'warning' : 'default'} /></TableCell><TableCell>★ {product.rating}</TableCell><TableCell align="right"><Button size="small" onClick={() => setDialog(product)}>Edit</Button><Button size="small" color="error" onClick={() => { if (window.confirm(`Delete ${product.title}?`)) { dispatch(deleteProduct(product.id)); setNotice('Product removed locally') } }}>Delete</Button></TableCell></TableRow>)}</TableBody></Table></Paper>}<ProductDialog key={dialog?.id || 'new'} value={dialog} categories={categories} close={() => setDialog(null)} save={(value) => { dialog?.id ? dispatch(updateProduct({ ...value, id: dialog.id })) : dispatch(addProduct(value)); setDialog(null); setNotice('Catalogue saved locally') }} /><Typography variant="caption">{notice}</Typography></Shell> }
export default AdminProducts
