import { useState } from 'react'
import { Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { Search } from '@mui/icons-material'
import { useDispatch, useSelector } from 'react-redux'
import { fetchOrders } from '../features/orders/ordersSlice'
import Shell from '../components/Shell'; import navItems from '../components/navItems'; import PageHeader from '../components/PageHeader'; import Status from '../components/Status'

const Orders = () => { const dispatch = useDispatch(); const { items, status, error } = useSelector((state) => state.orders); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const list = items.filter((order) => String(order.id).includes(query) || String(order.userId).includes(query)); return <Shell admin navItems={navItems}><PageHeader eyebrow="In progress" title="Order management" subtitle="Cart-backed order listing prepared for future status updates." /><TextField className="toolbar-search" size="small" placeholder="Filter by order or user ID" value={query} onChange={(event) => setQuery(event.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search fontSize="small" /></InputAdornment> } }} /><Status status={status} error={error} retry={() => dispatch(fetchOrders())} />{status === 'succeeded' && <Paper className="table-wrap"><Table size="small"><TableHead><TableRow><TableCell>Order ID</TableCell><TableCell>User ID</TableCell><TableCell>Products</TableCell><TableCell>Quantity</TableCell><TableCell>Total</TableCell><TableCell>Discount</TableCell><TableCell>Status</TableCell><TableCell /></TableRow></TableHead><TableBody>{list.map((order) => <TableRow key={order.id}><TableCell>#{order.id}</TableCell><TableCell>{order.userId}</TableCell><TableCell>{order.totalProducts}</TableCell><TableCell>{order.totalQuantity}</TableCell><TableCell>${order.total}</TableCell><TableCell>{order.discountedTotal ? `${Math.round((1 - order.discountedTotal / order.total) * 100)}%` : '—'}</TableCell><TableCell><Chip size="small" label="Pending" color="warning" /></TableCell><TableCell><Button onClick={() => setSelected(order)}>Details</Button></TableCell></TableRow>)}</TableBody></Table></Paper>}<Dialog open={!!selected} onClose={() => setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>Order #{selected?.id}</DialogTitle><DialogContent>{selected && <Stack spacing={1}>{selected.products.map((product) => <Stack key={product.id} direction="row" justifyContent="space-between"><Typography>{product.title} × {product.quantity}</Typography><Typography>${product.total}</Typography></Stack>)}<Divider /><Typography variant="h6">Total ${selected.total}</Typography></Stack>}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog></Shell> }
export default Orders
