import { useState } from 'react'
import { Avatar, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, InputAdornment, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField } from '@mui/material'
import { Search } from '@mui/icons-material'
import { useDispatch, useSelector } from 'react-redux'
import { fetchUsers } from '../features/users/usersSlice'
import Shell from '../components/Shell'; import navItems from '../components/navItems'; import PageHeader from '../components/PageHeader'; import Status from '../components/Status'

const Users = () => { const dispatch = useDispatch(); const { items, status, error } = useSelector((state) => state.users); const [query, setQuery] = useState(''); const [selected, setSelected] = useState(null); const list = items.filter((user) => `${user.firstName} ${user.lastName} ${user.username}`.toLowerCase().includes(query.toLowerCase())); return <Shell admin navItems={navItems}><PageHeader eyebrow="In progress" title="User management" subtitle="Customer directory and detail view. Activation and deletion are next." /><TextField className="toolbar-search" size="small" placeholder="Search users" value={query} onChange={(event) => setQuery(event.target.value)} slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search fontSize="small" /></InputAdornment> } }} /><Status status={status} error={error} retry={() => dispatch(fetchUsers())} />{status === 'succeeded' && <Paper className="table-wrap"><Table size="small"><TableHead><TableRow><TableCell>User</TableCell><TableCell>Email</TableCell><TableCell>Username</TableCell><TableCell>Gender</TableCell><TableCell>Age</TableCell><TableCell>Status</TableCell><TableCell /></TableRow></TableHead><TableBody>{list.map((user) => <TableRow key={user.id}><TableCell><Stack direction="row" spacing={1} alignItems="center"><Avatar src={user.image} />{user.firstName} {user.lastName}</Stack></TableCell><TableCell>{user.email}</TableCell><TableCell>{user.username}</TableCell><TableCell>{user.gender}</TableCell><TableCell>{user.age}</TableCell><TableCell><Chip size="small" label="Active" color="success" /></TableCell><TableCell><Button onClick={() => setSelected(user)}>Details</Button></TableCell></TableRow>)}</TableBody></Table></Paper>}<Dialog open={!!selected} onClose={() => setSelected(null)}><DialogTitle>User details</DialogTitle><DialogContent>{selected && <Stack spacing={1}><strong>{selected.firstName} {selected.lastName}</strong><span>{selected.email}</span><span>Company: {selected.company?.name}</span><span>Address: {selected.address?.address}, {selected.address?.city}</span></Stack>}</DialogContent><DialogActions><Button onClick={() => setSelected(null)}>Close</Button></DialogActions></Dialog></Shell> }
export default Users
